import {sources} from './lib/sources.js';
import {matchesKeywords,normalizeFilters,terms} from './lib/keyword-filter.js';
const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const categories=['자금·보증','바우처','마케팅','국내판로','수출·해외판로','기타 지원'];const states=['미검토','관심','검토 중','준비 중','신청 완료','선정','미선정','보류'];
const key='beauty-support-desk-v1';let view='all',keyword='',metric='',busy=false;
const seed={id:'https://kr.gobizkorea.com/support/ebsns/supporteBsnsInfo.do?svc=e8',title:'2026년 온라인수출 중소기업 물류 지원 사업',source:'gobiz',category:'수출·해외판로',url:'https://kr.gobizkorea.com/support/ebsns/supporteBsnsInfo.do?svc=e8',support:'풀필먼트 및 지정 해외물류센터 이용료 70% 지원. 서비스별 한도·조건은 공고문 확인.',conditions:'온라인수출(예정) 중소기업. 서비스별 계약 또는 이용증빙 필요. 체납·휴폐업 등 제외조건 확인.',deadline:'2026-09-16',deadlineTime:'18:00',status:'미검토',owner:'',note:'초기 등록: 2026-09-14 공식 원문 확인. 페이지 내 모집 차수 표기가 서로 달라 신청 전 최신 첨부 공고 확인 필요. 조기 마감 가능.',checkedAt:'2026-09-14T14:00:00Z',verification:'공식 원문 확인',manual:true};
let data;try{data=JSON.parse(localStorage.getItem(key))}catch{}if(!data||!Array.isArray(data.items))data={items:[seed],sources:{},deleted:[]};data.sources??={};data.deleted??=[];data.keywordFilters=normalizeFilters(data.keywordFilters);
function save(){try{localStorage.setItem(key,JSON.stringify(data));return true}catch{toast('저장 공간에 문제가 있습니다. 백업을 다운로드해 주세요.');return false}}
function toast(s){$('#toast').textContent=s;$('#toast').hidden=false;clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>$('#toast').hidden=true,6500)}
function today(){return new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Seoul',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date())}
function days(r){return /^\d{4}-\d{2}-\d{2}$/.test(r.deadline)?Math.round((Date.parse(r.deadline+'T00:00:00Z')-Date.parse(today()+'T00:00:00Z'))/864e5):null}
function closed(r){if(!r.deadline)return false;return r.deadlineTime?Date.now()>Date.parse(r.deadline+'T'+r.deadlineTime+':00+09:00'):days(r)<0}
function sourceName(id){return sources.find(s=>s.id===id)?.name||'직접 등록'}
function safeUrl(url){try{const u=new URL(url);return ['http:','https:'].includes(u.protocol)?u.href:''}catch{return ''}}
const opts=arr=>arr.map(v=>`<option value="${esc(v)}">${esc(v)}</option>`).join('');
$('#source').innerHTML+=sources.map(s=>`<option value="${s.id}">${s.name}</option>`).join('');$('#category').innerHTML+=opts(categories);$('#state').innerHTML+=opts(states);$('#edit-category').innerHTML=opts(categories);$('#edit-status').innerHTML=opts(states);$('#edit-source').innerHTML='<option value="manual">직접 등록</option>'+sources.map(s=>`<option value="${s.id}">${s.name}</option>`).join('');
function renderKeywords(){
 const mode=$('#keyword-mode').value;
 document.querySelectorAll('[data-key]').forEach(b=>{const active=b.dataset.key===keyword&&(mode==='any'||!keyword);b.classList.toggle('active',active);b.setAttribute('aria-pressed',String(active));});
 $('#saved-keywords').innerHTML=data.keywordFilters.map((f,i)=>`<span class="saved-keyword"><button class="chip ${f.query===keyword&&f.mode===mode?'active':''}" data-saved-key="${i}" aria-pressed="${f.query===keyword&&f.mode===mode}">${esc(f.query)} · ${f.mode==='all'?'AND':'OR'}</button><button class="remove-keyword" data-remove-key="${i}" aria-label="${esc(f.query)} 저장 키워드 삭제">×</button></span>`).join('');
 $('#keyword-current').textContent=terms(keyword).length?`적용 중: ${terms(keyword).join(mode==='all'?' + ':' / ')} · ${mode==='all'?'모두 포함':'하나라도 포함'}`:'키워드 제한 없음';
}
function setKeyword(query,mode='any'){keyword=query;$('#keyword-query').value=query.replaceAll('|',', ');$('#keyword-mode').value=mode;render();}
$('#keyword-query').addEventListener('input',()=>{keyword=$('#keyword-query').value;render()});
$('#keyword-mode').addEventListener('input',render);
$('#keyword-clear').onclick=()=>setKeyword('');
$('#keyword-form').onsubmit=e=>{e.preventDefault();const query=$('#keyword-query').value.trim(),mode=$('#keyword-mode').value;if(!terms(query).length)return toast('저장할 키워드를 입력하세요.');if(data.keywordFilters.some(f=>f.query===query&&f.mode===mode))return toast('이미 저장한 키워드입니다.');if(data.keywordFilters.length>=30)return toast('키워드는 30개까지 저장할 수 있습니다. 사용하지 않는 키워드를 삭제해 주세요.');data.keywordFilters.push({query,mode});if(save()){setKeyword(query,mode);toast('키워드를 저장했습니다.');}};
function render(){
 renderKeywords();
 const all=data.items;$('#total').textContent=all.length;$('#soon').textContent=all.filter(r=>days(r)!==null&&days(r)<=7&&!closed(r)).length;$('#interest').textContent=all.filter(r=>['관심','검토 중','준비 중'].includes(r.status)).length;$('#applied').textContent=all.filter(r=>r.status==='신청 완료').length;
 $('#list-panel').hidden=view==='sources';$('#source-panel').hidden=view!=='sources';$('#heading').textContent=({all:'지원사업 한눈에',interest:'관심·신청 관리',closed:'마감된 사업',sources:'수집 기관 관리'})[view];document.querySelectorAll('.nav').forEach(b=>b.classList.toggle('active',b.dataset.view===view));
 let rows=all.filter(r=>{const text=[r.title,r.support,r.conditions,sourceName(r.source),r.category].join(' ');return (!$('#search').value||text.toLowerCase().includes($('#search').value.toLowerCase()))&&(!$('#source').value||r.source===$('#source').value)&&(!$('#category').value||r.category===$('#category').value)&&(!$('#state').value||r.status===$('#state').value)&&matchesKeywords(text,keyword,$('#keyword-mode').value)&&(view!=='closed'||closed(r))&&(view!=='interest'||r.status!=='미검토')&&(metric!=='soon'||days(r)!==null&&days(r)<=7&&!closed(r))&&(metric!=='applied'||r.status==='신청 완료');});
 rows.sort((a,b)=>$('#sort').value==='recent'?(b.checkedAt||'').localeCompare(a.checkedAt||''):(a.deadline||'9999').localeCompare(b.deadline||'9999'));
 $('#count').textContent=rows.length;$('#empty').hidden=rows.length>0;$('#rows').innerHTML=rows.map(r=>{const d=days(r),url=safeUrl(r.url);return `<tr><td><span class="tag">${esc(r.category)}</span><br>${url?`<a href="${esc(url)}" target="_blank" rel="noopener noreferrer">${esc(r.title)} ↗</a>`:esc(r.title)}<div class="row-source">${esc(sourceName(r.source))} · ${esc(r.verification||'직접 등록')}</div></td><td><div class="cell-text">${esc(r.support||'원문 확인 필요')}</div></td><td><div class="cell-text">${esc(r.conditions||'원문 확인 필요')}</div></td><td>${r.deadline?esc(r.deadline):'<span class="muted">원문 확인 필요</span>'}${r.deadlineTime?`<div class="muted">${esc(r.deadlineTime)} (KST)</div>`:''}${d!==null?`<br><span class="dday ${closed(r)?'closed':''}">${closed(r)?'마감':d===0?'오늘 마감':'D-'+d}</span>`:''}</td><td><select class="state-select" aria-label="${esc(r.title)} 진행 상태" data-status="${esc(r.id)}">${states.map(s=>`<option ${s===r.status?'selected':''}>${s}</option>`).join('')}</select>${r.note?'<div class="row-source">메모 있음</div>':''}</td><td><button class="edit-btn" data-edit="${esc(r.id)}">상세·수정</button></td></tr>`}).join('');
 $('#source-cards').innerHTML=sources.map(s=>{const x=data.sources[s.id];return `<article class="source-card"><h3>${s.name}</h3><span class="source-status">${x?({partial:'일부 수집',error:'연결 실패',unavailable:'연동 보완 필요'})[x.status]||'확인 필요':'아직 수집하지 않음'}</span><p>${esc(x?.message||'기관별 새로고침으로 수집 가능 여부를 확인하세요.')}</p><div class="muted">최근 시도: ${x?new Date(x.checkedAt).toLocaleString('ko-KR',{timeZone:'Asia/Seoul'}):'없음'}</div><p><button data-refresh="${s.id}" ${busy?'disabled':''}>↻ 새로고침</button><a href="${s.url}" target="_blank" rel="noopener noreferrer">기관 방문 ↗</a></p></article>`}).join('');
}
function edit(id){const r=data.items.find(r=>r.id===id)||{id:'',title:'',source:'manual',category:categories[0],status:'미검토'};$('#form').reset();for(const [k,v]of Object.entries(r)){const el=$('#form').elements.namedItem(k);if(el&&typeof v==='string')el.value=v}$('#delete').hidden=!id;$('#dialog-title').textContent=id?'지원사업 상세·수정':'지원사업 등록';$('#editor').showModal()}
async function refresh(ids){if(busy)return;busy=true;$('#refresh').disabled=true;$('#refresh').textContent='수집 중…';render();let added=0,failed=0;await Promise.all(ids.map(async id=>{try{const res=await fetch('/api/refresh',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({source:id}),signal:AbortSignal.timeout(45000)});if(!res.ok)throw Error('수집 서버 응답 오류');const r=await res.json();data.sources[id]={status:r.status,message:r.message,checkedAt:r.checkedAt};if(r.status!=='partial')failed++;for(const item of r.items||[]){if(data.deleted.includes(item.id))continue;const old=data.items.find(i=>i.id===item.id);if(old){old.checkedAt=item.checkedAt;if(!old.manual)old.title=item.title;}else{data.items.push(item);added++;}}}catch(e){failed++;data.sources[id]={status:'error',message:'수집 서버에 연결하지 못했습니다. 기존 공고는 유지됩니다.',checkedAt:new Date().toISOString()}}render()}));save();busy=false;$('#refresh').disabled=false;$('#refresh').textContent='↻ 공고 새로고침';$('#last').textContent='최근 갱신 '+new Date().toLocaleTimeString('ko-KR',{timeZone:'Asia/Seoul'});render();toast(`신규 ${added}건 추가 · ${failed}개 기관 확인 필요. 수집 기관 탭에서 결과를 확인하세요.`)}
$('#refresh').onclick=()=>refresh(sources.map(s=>s.id));$('#add').onclick=()=>edit();$('#close').onclick=()=>$('#editor').close();
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.view){view=b.dataset.view;metric='';render()}if(b.dataset.edit)edit(b.dataset.edit);if(b.dataset.refresh)refresh([b.dataset.refresh]);if(b.dataset.key!==undefined){setKeyword(b.dataset.key)}if(b.dataset.savedKey!==undefined){const f=data.keywordFilters[Number(b.dataset.savedKey)];if(f)setKeyword(f.query,f.mode)}if(b.dataset.removeKey!==undefined){data.keywordFilters.splice(Number(b.dataset.removeKey),1);save();render();toast('저장 키워드를 삭제했습니다. 현재 적용 중인 필터는 유지됩니다.')}if(b.dataset.metric){metric=b.dataset.metric;view=metric==='interest'?'interest':'all';render()}});
document.addEventListener('change',e=>{if(e.target.dataset.status){const r=data.items.find(r=>r.id===e.target.dataset.status);r.status=e.target.value;save();render()}});['search','source','category','state','sort'].forEach(id=>$('#'+id).addEventListener('input',render));
$('#form').onsubmit=e=>{e.preventDefault();const r=Object.fromEntries(new FormData(e.target));if(r.url&&!safeUrl(r.url))return toast('http 또는 https 주소를 입력하세요.');if(r.deadlineTime&&!r.deadline)return toast('마감시간을 입력하려면 마감일도 입력하세요.');if(!r.title.trim())return toast('사업명을 입력하세요.');r.title=r.title.trim();r.id=r.id||crypto.randomUUID();r.checkedAt=new Date().toISOString();r.manual=true;r.verification='직접 확인·입력';const index=data.items.findIndex(x=>x.id===r.id);if(index<0)data.items.push(r);else data.items[index]={...data.items[index],...r};if(save()){$('#editor').close();render();toast('저장했습니다.')}};
$('#delete').onclick=()=>{if(!confirm('이 공고를 삭제할까요? 새로고침으로 다시 추가되지 않습니다.'))return;const id=$('#form').elements.namedItem('id').value;data.items=data.items.filter(r=>r.id!==id);data.deleted.push(id);save();$('#editor').close();render()};
$('#export').onclick=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify({...data,version:1,exportedAt:new Date().toISOString()},null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=`beauty-support-backup-${today()}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
$('#import').onclick=()=>$('#file').click();$('#file').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{if(f.size>10e6)throw Error();const next=JSON.parse(await f.text());if(!Array.isArray(next.items)||!next.items.every(r=>typeof r.id==='string'&&typeof r.title==='string'&&typeof r.source==='string'&&(!r.url||safeUrl(r.url))))throw Error();if(!confirm(`${next.items.length}건을 가져올까요? 같은 ID는 현재 기록을 유지하고 새 항목과 저장 키워드를 추가합니다.`))return;for(const r of next.items)if(!data.items.some(x=>x.id===r.id))data.items.push({...r,status:states.includes(r.status)?r.status:'미검토'});data.keywordFilters=normalizeFilters([...data.keywordFilters,...normalizeFilters(next.keywordFilters)]);save();render();toast('백업을 가져왔습니다.')}catch{toast('올바른 백업 JSON 파일인지 확인해 주세요.')}finally{e.target.value=''}};
save();render();
