import * as planningData from './lib/planning-data.js';
import * as beautyData from './lib/beauty-data.js';
const beauty=document.body.dataset.workspace==='beauty';
const {commonTasks,programs,followups}=beauty?beautyData:planningData;
const workspace=beauty?'beauty-special':'planning-2027';
const KEY=beauty?'beauty-support-special-v1':'beauty-support-planning-2027-v1';
const $=s=>document.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const states=['검토 전','준비 중','준비 완료','보류','조건 미충족'];
const tasks=[...commonTasks.map(t=>({...t,id:'common-'+t.id})),...programs.flatMap(p=>p.tasks.map((title,i)=>({id:p.id+'-'+i,title,due:p.due})))];
const taskIds=new Set(tasks.map(t=>t.id)),programIds=new Set(programs.map(p=>p.id));
function clean(raw){
 if(!raw||typeof raw!=='object'||Array.isArray(raw))throw Error('잘못된 백업 형식입니다.');
 const result={tasks:{},programs:{}};
 for(const [id,v] of Object.entries(raw.tasks||{})){if(!taskIds.has(id)||!v||typeof v!=='object')continue;result.tasks[id]={done:v.done===true,owner:String(v.owner||'').slice(0,80),due:/^\d{4}-\d{2}-\d{2}$/.test(v.due)?v.due:'',note:String(v.note||'').slice(0,2000)};}
 for(const [id,v] of Object.entries(raw.programs||{})){if(!programIds.has(id)||!v||typeof v!=='object')continue;result.programs[id]={status:states.includes(v.status)?v.status:states[0],note:String(v.note||'').slice(0,6000),url:/^https?:\/\//.test(v.url)?String(v.url).slice(0,2000):'',deadline:/^\d{4}-\d{2}-\d{2}$/.test(v.deadline)?v.deadline:''};}
 return result;
}
let data={tasks:{},programs:{}};
try{const saved=localStorage.getItem(KEY);if(saved)data=clean(JSON.parse(saved));}catch{alert('저장 데이터를 읽지 못했습니다. 기존 저장값을 백업하기 전에는 변경하지 마세요.');}
function toast(message){$('#toast').textContent=message;$('#toast').hidden=false;clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').hidden=true,4500);}
function save(){try{localStorage.setItem(KEY,JSON.stringify(data));}catch{toast('저장 실패: 브라우저 저장 공간을 확인하고 백업을 다운로드하세요.');}}
function taskHTML(t){const v=data.tasks[t.id]||{};return `<div class="task ${v.done?'done':''}" data-task="${t.id}"><label class="check"><input type="checkbox" data-field="done" ${v.done?'checked':''}><span>${esc(t.title)}</span></label><label>담당자<input data-field="owner" aria-label="${esc(t.title)} 담당자" maxlength="80" value="${esc(v.owner)}"></label><label>내부 목표일<input type="date" data-field="due" aria-label="${esc(t.title)} 내부 목표일" value="${esc(v.due??t.due)}"></label><label>메모<input data-field="note" aria-label="${esc(t.title)} 메모" maxlength="2000" value="${esc(v.note)}"></label></div>`;}
function progress(){const done=tasks.filter(t=>data.tasks[t.id]?.done).length;$('#progress').textContent=`${done} / ${tasks.length}`;$('#common-progress').textContent=`${commonTasks.filter(t=>data.tasks['common-'+t.id]?.done).length} / ${commonTasks.length} 완료`;for(const el of document.querySelectorAll('[data-progress]')){const p=programs.find(p=>p.id===el.dataset.progress);el.textContent=`${p.tasks.filter((_,i)=>data.tasks[p.id+'-'+i]?.done).length}/${p.tasks.length} 완료`;}}
function renderPrograms(){const q=$('#search').value.trim().toLowerCase(),category=$('#category').value,priority=$('#priority').value,recurrence=$('#recurrence').value;const region=$('#region')?.value||'';const filtered=programs.filter(p=>(!region||p.region===region)&&(!q||[p.title,p.support,p.eligibility,p.agency,...p.tasks].join(' ').toLowerCase().includes(q))&&(!category||p.category===category)&&(!priority||p.priority===priority)&&(!recurrence||(recurrence==='repeat')===!!p.repeatUrl));$('#count').textContent=`${filtered.length}개`;$('#empty').hidden=filtered.length>0;
 $('#programs').innerHTML=filtered.map(p=>{const v=data.programs[p.id]||{};return `<details class="program" data-program="${p.id}"><summary><span class="title">${esc(p.title)}<br><small>${esc(p.agency)} · ${esc(p.category)}${p.region?' · '+esc(p.region):''}</small></span><span class="badge">${p.priority}</span><span class="badge ${p.repeatUrl?'':'pending'}">${esc(p.recurrence)}</span><small data-progress="${p.id}"></small><small>상세 보기 ▾</small></summary><dl class="facts"><div><dt>2025년 지원내용</dt><dd>${esc(p.support)}</dd></div><div><dt>지원조건 · 회사 조건 확인 필요</dt><dd>${esc(p.eligibility)}</dd></div><div><dt>과거 접수기간 / 게시일</dt><dd>${esc(p.period)}</dd></div><div><dt>공고 모니터링 권장 시기</dt><dd>${esc(p.monitor)} · 확정 일정 아님</dd></div></dl><p class="caution">${esc(p.caution)}</p><div class="citations"><a href="${esc(p.url)}" target="_blank" rel="noopener noreferrer">2025년 근거 공고 ↗</a>${p.extraUrl?`<a href="${esc(p.extraUrl)}" target="_blank" rel="noopener noreferrer">추가 근거 ↗</a>`:''}${p.repeatUrl?`<a href="${esc(p.repeatUrl)}" target="_blank" rel="noopener noreferrer">2026년 반복 확인 근거 ↗</a>`:''}</div><div class="tracking"><label>검토 상태<select data-program-field="status">${states.map(s=>`<option ${v.status===s?'selected':''}>${s}</option>`).join('')}</select></label><label>2027년 실제 공고 URL (확인 후 입력)<input type="url" data-program-field="url" maxlength="2000" placeholder="https://" value="${esc(v.url)}"></label><label>2027년 실제 마감일 (확인 후 입력)<input type="date" data-program-field="deadline" value="${esc(v.deadline)}"></label><label class="wide">회사 적합성 · 변경조건 메모<textarea data-program-field="note" rows="2" maxlength="6000">${esc(v.note)}</textarea></label></div><h3>사업별 실무 준비 권장안</h3>${p.tasks.map((title,i)=>taskHTML({id:p.id+'-'+i,title,due:p.due})).join('')}</details>`;}).join('');progress();}
$('#common-tasks').innerHTML=tasks.filter(t=>t.id.startsWith('common-')).map(taskHTML).join('');
$('#program-total').textContent=programs.length;$('#repeat-total').textContent=programs.filter(p=>p.repeatUrl).length;
$('#category').insertAdjacentHTML('beforeend',[...new Set(programs.map(p=>p.category))].map(c=>`<option>${esc(c)}</option>`).join(''));
$('#followups').innerHTML=followups.map(f=>`<article><a href="${esc(f.url)}" target="_blank" rel="noopener noreferrer">${esc(f.name)} ↗</a><p>${esc(f.reason)}</p></article>`).join('');
for(const id of ['search','category','priority','recurrence','region'])$('#'+id)?.addEventListener('input',renderPrograms);
document.addEventListener('input',e=>{const field=e.target.dataset.field,programField=e.target.dataset.programField;if(field){const row=e.target.closest('[data-task]'),id=row.dataset.task;const t=tasks.find(t=>t.id===id);data.tasks[id]??={due:t.due};data.tasks[id][field]=field==='done'?e.target.checked:e.target.value;row.classList.toggle('done',!!data.tasks[id].done);save();progress();}else if(programField){const id=e.target.closest('[data-program]').dataset.program;data.programs[id]??={};data.programs[id][programField]=e.target.value;save();}});
$('#export').onclick=()=>{const blob=new Blob([JSON.stringify({workspace,version:1,exportedAt:new Date().toISOString(),...data},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=beauty?'beauty-desk-special-backup.json':'beauty-desk-2027-backup.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
$('#import').onclick=()=>$('#file').click();$('#file').onchange=async e=>{try{const file=e.target.files[0];if(!file)return;if(file.size>2000000)throw Error('백업 파일은 2MB 이하로 선택하세요.');const raw=JSON.parse(await file.text());if(raw.workspace!==workspace||raw.version!==1)throw Error('현재 워크스페이스에서 내보낸 백업을 선택하세요.');const incoming=clean(raw);if(!confirm('백업에 포함된 작업과 사업의 저장값을 덮어씁니다. 현재 내용을 백업했다면 계속하세요.'))return;data={tasks:{...data.tasks,...incoming.tasks},programs:{...data.programs,...incoming.programs}};save();$('#common-tasks').innerHTML=tasks.filter(t=>t.id.startsWith('common-')).map(taskHTML).join('');renderPrograms();toast('백업을 가져왔습니다.');}catch(err){toast(err.message);}finally{e.target.value='';}};
renderPrograms();
